
import numpy as np

# arr1=np.random.randint(100,size=(4,4))
# arr2=np.random.randint(100,size=(4,4))
# print(arr1)
# print("--------------------------------")
# print(arr2)

arr2=np.asarray([[1,2,3],[1,3,2]])
arr1=np.asarray([[1,2],[1,2],[3,4]])
arr2
# arr3=arr1.arr2
arr3=np.dot(arr1,arr2)
print()
print(arr1.shape)
arr3

# def is_prime(n):
#     for i in range(2,n):p
#         if n%i==0:
#             return False
  
#     return True



# no=222222
# sum=0
# for i in range(2,no**(1/2)):
#     if (no%i==0 and is_prime(i)):
#        print(i)
        

# print(sum) 



# l=(12,3,4,1,23,2)

# b=[10*i for i in range(10) if i<10 ]
# print(b)




# for i,item in enumerate(l):
#     print(i,item)


# name=in